# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install musescore 3.6
        run: |
          sudo add-apt-repository ppa:mscore-ubuntu/mscore3-stable
          sudo apt-get update
          sudo apt-get install musescore3 qt5-default
      # Runs a single command using the runners shell
      - name: Run Makefile to make PDFs, MP3s, etc
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./ #optional
          run: make      
      - name: Add Commit and Push
        run: |
          git config --global user.email "chris.j.woodall+musescorebot@gmail.com"
          git config --global user.name "MuseScore 3 Bot"
          git add .
          git commit -am "Updating pdfs and mp3s"
          git push
        
